### PR TITLE
Added ResponseConverter Middleware

### PR DESCRIPTION
**Pull request by xepozz**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ✔️
| Breaks BC?    | ✔️
| Tests pass?   | ✔️

Example of usage you can see this https://github.com/yiisoft/yii-demo/pull/71

### CODE REVIEW

**Comment by samdark** [comment]
Related to https://github.com/yiisoft/yii-demo/pull/73

**Comment by samdark** [comment]
Compared to https://github.com/yiisoft/yii-demo/pull/73 this solution:

1. ➖  Is action caller middleware only. Duplicates router functionality.
2. ➕  Can return data from action directly. Syntax is shorter.
3. ➖ It is not clear about how to add additional headers to response.

**Comment by samdark** [comment]
For now I'd prefer https://github.com/yiisoft/yii-demo/pull/73 solution.

**Comment by xepozz** [comment]
If you want to add headers from controller you should inject the ResponseFactory into your action/controller, create Response and add headers.

**Comment by samdark** [comment]
For now decided to go with https://github.com/yiisoft/yii-demo/pull/73

**Pull request closed without merging**
